kind: pipeline
type: docker
name: default

steps:
  - name: Tests
    image: alpine:3.15.0
    commands:
      - docker-compose run --rm db-migrations
      - docker-compose up -d
      - docker-compose run --rm tests
