version: '3.9'

services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - 5432:5432

  db-migrations:
    image: amacneil/dbmate:v1.12.0
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/auth?sslmode=disable
    volumes:
      - "./db:/db:ro"
    command: --wait up
    profiles: ["migrations"]
    depends_on:
      - postgres

  auth:
    build: .
    environment:
      - ADMIN_API_KEY=hihi
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/auth?sslmode=disable
      - JWT_SHARED_SECRET=hihi
      - WEB_BIND_HOST=:4000
    depends_on:
      - postgres
    ports:
      - 4000:4000